displayName=DVD Bounce
author=vividflash
description=A picture bounces around your client like the DVD screensaver. Will hit the corner.
tags=dvd,bounce,screensaver,overlay,fun
plugins=com.vividflash.dvdbounce.DvdBouncePlugin
build=standard
version=1.1.1
