displayName=DVD Bounce
author=vividflash
description=Item or your own image bounces like the DVD logo
tags=dvd,bounce,screensaver,overlay,item,fun
plugins=com.vividflash.dvdbounce.DvdBouncePlugin
build=standard
version=1.6
