displayName=DVD Bounce
author=vividflash
description=An item or your own picture bounces around the client like the DVD screensaver. Will hit the corner.
tags=dvd,bounce,screensaver,overlay,item,fun
plugins=com.vividflash.dvdbounce.DvdBouncePlugin
build=standard
version=1.6
